<?php
/**
 * Copyright © 2017 Dxvn, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for \Diepxuan\Catalog\Block\Adminhtml\Category\PositionProducts
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 */

/**
 * @var \Diepxuan\Catalog\Block\Adminhtml\Category\Tab\Position $block
 */
?>
<?php if ($block->getCollection()): ?>
<div id="<?php echo $block->escapeHtml($block->getId()) ?>"
    data-position-id="<?php echo $block->escapeHtml($block->getId()) ?>">
    <div class="evolve-retail-top-action">
        <ul>
            <li><button id="reindexAllProduct" ><span>set automatic</span></button></li>
        </ul>
    </div>
    <div class="merchandiser-content">
        <ul id="evolve-merchandiser" class="ui-sortable">
            <?php foreach ($block->getCollection() as $index => $_item) : ?>
            <li class="ui-sortable-handle evol-merchan-item">
                <?php foreach ($block->getColumns() as $_column) : ?>
                <div class="item <?php /* @escapeNotVerified */ echo $_column->getCssProperty() ?>">
                    <?php echo(($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?>
                </div>
                <?php endforeach; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif ?>
