<?php

/**
 * Copyright © 2017 Dxvn, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Diepxuan\Catalog\Block\Adminhtml\Category\PositionProducts $block */

/** @var \Diepxuan\Catalog\Block\Adminhtml\Category\Tab\Position $blockGrid */
$blockGrid = $block->getBlockGrid();
?>
<?php echo $block->getGridHtml(); ?>
<input type="hidden" name="position_products" id="in_position_products" data-form-part="category_form" value="" />
<script type="text/x-magento-init">
    {
        "[data-position-id=<?php /* @escapeNotVerified */ echo $block->escapeHtml($blockGrid->getId())  ?: ''; ?>]": {
            "Diepxuan_Catalog/catalog/category/position-products": {}
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
